-- MySQL Script generated by MySQL Workbench
-- Sun Dec  3 17:21:07 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student` ;

CREATE TABLE IF NOT EXISTS `Student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Class` ;

CREATE TABLE IF NOT EXISTS `Class` (
  `class_id` INT NOT NULL,
  `grade` VARCHAR(50) NOT NULL,
  `teacher` VARCHAR(45) NOT NULL,
  `room` VARCHAR(45) NOT NULL COMMENT 'a room have never more than one teacher',
  PRIMARY KEY (`class_id`),
  UNIQUE INDEX `teacher_UNIQUE` (`teacher` ASC),
  UNIQUE INDEX `room_UNIQUE` (`room` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student_in_Class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student_in_Class` ;

CREATE TABLE IF NOT EXISTS `Student_in_Class` (
  `Student_student_id` INT NOT NULL,
  `Class_room` INT NOT NULL,
  PRIMARY KEY (`Student_student_id`, `Class_room`),
  INDEX `fk_Student_has_Class_Class1_idx` (`Class_room` ASC),
  INDEX `fk_Student_has_Class_Student_idx` (`Student_student_id` ASC),
  CONSTRAINT `fk_Student_has_Class_Student`
    FOREIGN KEY (`Student_student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Class_Class1`
    FOREIGN KEY (`Class_room`)
    REFERENCES `Class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Question` ;

CREATE TABLE IF NOT EXISTS `Question` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL COMMENT '1 of multiple true-false, numeric',
  `text` VARCHAR(45) NOT NULL COMMENT 'question sentence',
  PRIMARY KEY (`question_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MultipleChoiceOption`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MultipleChoiceOption` ;

CREATE TABLE IF NOT EXISTS `MultipleChoiceOption` (
  `MultipleChoiceQuestion_question_id` INT NOT NULL,
  `text` VARCHAR(100) NOT NULL,
  INDEX `fk_MultipleChoiceOptions_MultipleChoiceQuestion1_idx` (`MultipleChoiceQuestion_question_id` ASC),
  PRIMARY KEY (`MultipleChoiceQuestion_question_id`, `text`),
  CONSTRAINT `fk_MultipleChoiceOptions_MultipleChoiceQuestion1`
    FOREIGN KEY (`MultipleChoiceQuestion_question_id`)
    REFERENCES `MultipleChoiceQuestion` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MultipleChoiceQuestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MultipleChoiceQuestion` ;

CREATE TABLE IF NOT EXISTS `MultipleChoiceQuestion` (
  `question_id` INT NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_MultipleChoiceQuestion_Question1_idx` (`question_id` ASC),
  INDEX `fk_MultipleChoiceQuestion_MultipleChoiceOptions1_idx` (`answer` ASC),
  CONSTRAINT `fk_MultipleChoiceQuestion_Question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `Question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MultipleChoiceQuestion_MultipleChoiceOptions1`
    FOREIGN KEY (`answer`)
    REFERENCES `MultipleChoiceOption` (`text`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrueFalseQuestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrueFalseQuestion` ;

CREATE TABLE IF NOT EXISTS `TrueFalseQuestion` (
  `question_id` INT NOT NULL,
  `answer` TINYINT(1) NOT NULL COMMENT 'either true or false ',
  PRIMARY KEY (`question_id`),
  CONSTRAINT `fk_TrueFalseQuestion_Question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `Question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NumericQuestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NumericQuestion` ;

CREATE TABLE IF NOT EXISTS `NumericQuestion` (
  `question_id` INT NOT NULL,
  `answer` INT NOT NULL,
  PRIMARY KEY (`question_id`),
  INDEX `fk_NumericQuestion_Question1_idx` (`question_id` ASC),
  CONSTRAINT `fk_NumericQuestion_Question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `Question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NumericQuestionHint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NumericQuestionHint` ;

CREATE TABLE IF NOT EXISTS `NumericQuestionHint` (
  `NumericQuestion_question_id` INT NOT NULL COMMENT 'question id, lower and upper bound forms a key',
  `lower_bound` INT NOT NULL,
  `upper_bound` INT NOT NULL,
  `text` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`NumericQuestion_question_id`, `lower_bound`, `upper_bound`),
  CONSTRAINT `fk_NumericQuestionHint_NumericQuestion1`
    FOREIGN KEY (`NumericQuestion_question_id`)
    REFERENCES `NumericQuestion` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Quiz` ;

CREATE TABLE IF NOT EXISTS `Quiz` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `due` DATETIME NOT NULL,
  `class_id` INT NOT NULL,
  `hint_flag` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_Quiz_Class1_idx` (`class_id` ASC),
  CONSTRAINT `fk_Quiz_Class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `Class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuizQuestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `QuizQuestion` ;

CREATE TABLE IF NOT EXISTS `QuizQuestion` (
  `quiz_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `weight` INT NOT NULL,
  PRIMARY KEY (`quiz_id`, `question_id`),
  INDEX `fk_QuizQuestion_Question1_idx` (`question_id` ASC),
  CONSTRAINT `fk_QuizQuestion_Quiz1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `Quiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QuizQuestion_Question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `Question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MultipleChoiceAnswer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MultipleChoiceAnswer` ;

CREATE TABLE IF NOT EXISTS `MultipleChoiceAnswer` (
  `question_id` INT NOT NULL,
  `answer` VARCHAR(100) NOT NULL,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`question_id`, `student_id`),
  INDEX `fk_MultipleChoiceAnswer_MultipleChoiceOption1_idx` (`answer` ASC),
  INDEX `fk_MultipleChoiceAnswer_Student1_idx` (`student_id` ASC),
  CONSTRAINT `fk_MultipleChoiceAnswer_Question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `Question` (`question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MultipleChoiceAnswer_MultipleChoiceOption1`
    FOREIGN KEY (`answer`)
    REFERENCES `MultipleChoiceOption` (`text`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MultipleChoiceAnswer_Student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
